# Конфигурация Air для Go проекта

# Корневая директория, где Air будет запускать команды
root = "."
# Путь к исполняемому файлу (бинарнику), который будет сгенерирован
bin = "./tmp/main"
# Команды для сборки проекта
cmd = "go build -o ./tmp/main ."
# Файлы и директории для наблюдения
watch_dir = ["."]
# Файлы и директории, которые следует исключить из наблюдения
exclude_dir = ["tmp"]
# Файлы, которые следует исключить из наблюдения (можно использовать паттерны)
exclude_file = []
# Файлы с указанными расширениями будут отслеживаться
include_ext = ["go", "tpl", "tmpl", "html"]
# Флаг, указывающий на необходимость следить за изменениями во всех директориях
follow_symlinks = false
# Интервал (в секундах) для опроса файлов на предмет изменений
delay = 1000 # 1 секунда
# Настройка логирования
log_level = "info"

[log]
time = true

